version: '3.9'
services:
  backend:
    container_name: rjournal.backend
    image: node:17-alpine3.14
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    networks:
      - postgres
      - api
    restart: always
    command: sh -c "cd /app; yarn install; yarn run dev"

networks:
  postgres:
    external: true
    name: 'rjournal_postgres'
    driver: bridge
  api:
    driver: bridge
