version: '3.9'
services:
  web:
    image: node:17-alpine3.14
    ports:
      - '3001:3001'
    volumes:
      - '.:/app'
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    command: sh -c "cd /app; yarn install; yarn run start:dev"
